var _ = require('lodash');

module.exports = {
  POOL: _.isNumber,
  URL: _.isString,
  Status: _.isString,
  Priority: _.isNumber,
  'Long Poll': _.isString,
  Getworks: _.isNumber,
  Accepted: _.isNumber,
  Rejected: _.isNumber,
  Discarded: _.isNumber,
  Stale: _.isNumber,
  'Get Failures': _.isNumber,
  'Remote Failures': _.isNumber,
  User: _.isString,
  'Last Share Time': _.isNumber,
  'Diff1 Shares': _.isNumber,
  'Proxy Type': _.isString,
  Proxy: _.isString,
  'Difficulty Accepted': _.isNumber,
  'Difficulty Rejected': _.isNumber,
  'Last Share Difficulty': _.isNumber,
  'Difficulty Stale': _.isNumber,
  'Has Stratum': _.isBoolean,
  'Statum Active': _.isBoolean,
  'Stratum URL': _.isString,
  'Has GBT': _.isBoolean,
  'Best Share': _.isNumber
};

/**
{ POOL: 0,
    URL: 'stratum+tcp://stratum.mining.eligius.st:3334',
    Status: 'Alive',
    Priority: 0,
    'Long Poll': 'N',
    Getworks: 2094,
    Accepted: 0,
    Rejected: 0,
    Discarded: 4174,
    Stale: 0,
    'Get Failures': 0,
    'Remote Failures': 0,
    User: '16GgJNQDHxx2NpjSxgrAAndnSEjBR4uBTt',
    'Last Share Time': 0,
    'Diff1 Shares': 0,
    'Proxy Type': '',
    Proxy: '',
    'Difficulty Accepted': 0,
    'Difficulty Rejected': 0,
    'Difficulty Stale': 0,
    'Last Share Difficulty': 0,
    'Has Stratum': true,
    'Stratum Active': true,
    'Stratum URL': 'stratum.mining.eligius.st',
    'Has GBT': false,
    'Best Share': 0 }
*/
