var _ = require('lodash');

module.exports = {
  ID: _.isString,
  Elapsed: _.isNumber,
  Calls: _.isNumber,
  Wait: _.isNumber,
  Max: _.isNumber,
  Min: _.isNumber,
  'Pool Calls': _.isNumber,
  'Pool Attempts': _.isNumber,
  'Pool Wait': _.isNumber,
  'Pool Max': _.isNumber,
  'Pool Min': _.isNumber,
  'Pool Av': _.isNumber,
  'Work Had Roll Time': _.isBoolean,
  'Work Can Roll': _.isBoolean,
  'Work Had Expire': _.isBoolean,
  'Work Roll Time': _.isNumber,
  'Work Diff': _.isNumber,
  'Min Diff': _.isNumber,
  'Max Diff': _.isNumber,
  'Min Diff Count': _.isNumber,
  'Max Diff Count': _.isNumber,
  'Times Sent': _.isNumber,
  'Bytes Sent': _.isNumber,
  'Times Recv': _.isNumber,
  'Bytes Recv': _.isNumber,
  'Net Bytes Sent': _.isNumber,
  'Net Bytes Recv': _.isNumber
};

/**
STATS: 1,
       ID: 'POOL0',
       Elapsed: 126305,
       Calls: 118751,
       Wait: 179.161207,
       Max: 0.241397,
       Min: 0,
       'Pool Calls': 0,
       'Pool Attempts': 0,
       'Pool Wait': 0,
       'Pool Max': 0,
       'Pool Min': 99999999,
       'Pool Av': 0,
       'Work Had Roll Time': false,
       'Work Can Roll': false,
       'Work Had Expire': false,
       'Work Roll Time': 0,
       'Work Diff': 127,
       'Min Diff': 127,
       'Max Diff': 127,
       'Min Diff Count': 13627,
       'Max Diff Count': 13627,
       'Times Sent': 4,
       'Bytes Sent': 218,
       'Times Recv': 4510,
       'Bytes Recv': 32612420,
       'Net Bytes Sent': 218,
       'Net Bytes Recv': 32612420
*/


